version: "3.7"

services:
  main:
    container_name: main
    build:
      context: .
      target: development #production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start
    restart: always
